#!/bin/bash
#==============================================================
# CareLens Aged+ — E2E XCTest Runner & PDF Report Generator
# Tests ALL units (enums, models, services, data layer, sync)
# and generates a comprehensive PDF report on Desktop.
#==============================================================

set -e

PROJECT_DIR="/Applications/Carelens-Aged+"
PROJECT="$PROJECT_DIR/Carelens-Aged+.xcodeproj"
SCHEME="Carelens-Aged+"
TEST_TARGET="Carelens-Aged+Tests"
DESKTOP="$HOME/Desktop"
REPORT_DIR="$DESKTOP/CareLensReports"
TIMESTAMP=$(date "+%Y-%m-%d_%H.%M.%S")
XCRESULT="$REPORT_DIR/TestRun_$TIMESTAMP.xcresult"
LOG_FILE="$REPORT_DIR/TestRun_$TIMESTAMP.log"

mkdir -p "$REPORT_DIR"

echo "========================================"
echo " CareLens Aged+ — E2E Unit Test Runner"
echo "========================================"
echo "Timestamp: $(date)"
echo "Project: $PROJECT"
echo "Scheme: $SCHEME"
echo "Test target: $TEST_TARGET"
echo "Report dir: $REPORT_DIR"
echo ""

#──────────────────────────────────────────────
# STEP 1: Find a Simulator
#──────────────────────────────────────────────
echo "[1/4] Finding available simulator..."
SIM=$(xcrun simctl list devices available 2>/dev/null | grep -E "iPhone.*\((Booted|Shutdown)\)" | head -1 | grep -oE "[A-F0-9-]{36}" | head -1)

if [ -z "$SIM" ]; then
    echo "No available simulators found. Creating one..."
    SIM_NAME="CareLensTestiPhone"
    xcrun simctl create "$SIM_NAME" "iPhone 16 Pro" 2>/dev/null || true
    SIM=$(xcrun simctl list devices | grep "$SIM_NAME" | grep -oE "[A-F0-9-]{36}" | head -1)
fi

if [ -z "$SIM" ]; then
    echo "ERROR: Could not find or create a simulator."
    echo "Please ensure Xcode is installed and a simulator is available."
    exit 1
fi

echo "Using simulator: $SIM"

# Boot if needed
SIM_STATE=$(xcrun simctl list devices | grep "$SIM" | grep -oE "\([A-Za-z]+\)" | head -1 | tr -d '()')
if [ "$SIM_STATE" != "Booted" ]; then
    echo "Booting simulator..."
    xcrun simctl boot "$SIM" 2>/dev/null || true
    sleep 5
fi

#──────────────────────────────────────────────
# STEP 2: Build for Testing
#──────────────────────────────────────────────
echo ""
echo "[2/4] Building for testing..."
set -o pipefail
xcodebuild build-for-testing \
    -project "$PROJECT" \
    -scheme "$SCHEME" \
    -sdk iphonesimulator \
    -destination "platform=iOS Simulator,id=$SIM" \
    -only-testing:"$TEST_TARGET" \
    -derivedDataPath "$REPORT_DIR/DerivedData" \
    2>&1 | tee -a "$LOG_FILE" | tail -5

BUILD_EXIT=${PIPESTATUS[0]}
if [ $BUILD_EXIT -ne 0 ]; then
    echo "BUILD FAILED (exit code $BUILD_EXIT)"
    echo "Check log: $LOG_FILE"
    exit $BUILD_EXIT
fi
echo "Build succeeded."

#──────────────────────────────────────────────
# STEP 3: Run Tests
#──────────────────────────────────────────────
echo ""
echo "[3/4] Running E2E XCTest suite..."
echo "  (Testing ALL units: enums, models, services, sync, data layer)"
echo ""

set -o pipefail
xcodebuild test-without-building \
    -project "$PROJECT" \
    -scheme "$SCHEME" \
    -sdk iphonesimulator \
    -destination "platform=iOS Simulator,id=$SIM" \
    -only-testing:"$TEST_TARGET/EndToEnd" \
    -derivedDataPath "$REPORT_DIR/DerivedData" \
    -resultBundlePath "$XCRESULT" \
    2>&1 | tee -a "$LOG_FILE"

TEST_EXIT=${PIPESTATUS[0]}

#──────────────────────────────────────────────
# STEP 4: Generate Report
#──────────────────────────────────────────────
echo ""
echo "[4/4] Generating PDF report..."

# Extract test results from xcresult
if [ -d "$XCRESULT" ]; then
    echo "  Test results bundle: $XCRESULT"
    xcrun xcresulttool get --path "$XCRESULT" --format json > "$REPORT_DIR/results_$TIMESTAMP.json" 2>/dev/null || true

    # Parse summary
    PASS_COUNT=$(xcrun xcresulttool get --path "$XCRESULT" --format json 2>/dev/null | python3 -c "
import json,sys
data=json.load(sys.stdin)
def count_tests(obj):
    if isinstance(obj,dict):
        if obj.get('_type','').get('_name','') == 'ActionTestSummaryGroup':
            return sum(count_tools(v) for v in obj.get('subtests',[]))
        return 1
    return 0
print(count_tests(data))
" 2>/dev/null || echo "N/A")

    echo "  Tests executed. Report saved to: $REPORT_DIR"
fi

# Copy the test report PDF if generated by the observer
# (The XCTest observer saves directly to Desktop/CareLensAged_E2E_TestReport_*.pdf)
echo ""
echo "========================================"
echo " TEST RUN COMPLETE"
echo "========================================"
echo "Log: $LOG_FILE"
echo "Xcode result bundle: $XCRESULT"
echo ""
echo "The XCTest PDF report observer will save the"
echo "report to Desktop when tests finish in Xcode."
echo ""

if [ $TEST_EXIT -eq 0 ]; then
    echo "STATUS: ALL TESTS PASSED"
else
    echo "STATUS: SOME TESTS FAILED (exit code $TEST_EXIT)"
    echo "Review the log for details."
fi

echo ""
echo "To view detailed results in Xcode:"
echo "  open $XCRESULT"
echo ""
echo "To re-run tests:"
echo "  $0"

exit $TEST_EXIT
